module:
  address: 0
  aggiefeed: 0
  anchor_link: 0
  automated_cron: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  block_place: 0
  block_style_plugins: 0
  breakpoint: 0
  cas: 0
  ck_autosave: 0
  ck_feature_block: 0
  ck_media_link: 0
  ckeditor: 0
  ckwordcount: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_update: 0
  contact: 0
  content_audit: 0
  contextual: 0
  crop: 0
  ctools: 0
  daterange_compact: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  editor_file: 0
  embed: 0
  empty_fields: 0
  entity_reference: 0
  eva: 0
  external_media_embed: 0
  externalauth: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  focal_point: 0
  geolocation: 0
  google_analytics: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  link: 0
  lock_sitefarm_features: 0
  mailchimp: 0
  mailchimp_lists: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_ui: 0
  metatag: 0
  node: 0
  notification: 0
  options: 0
  page_cache: 0
  path: 0
  photoswipe: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redis: 0
  robotstxt: 0
  roleassign: 0
  rss_feed_block: 0
  scheduled_updates: 0
  search: 0
  sharemessage: 0
  shortcut: 0
  simple_sitemap: 0
  site_credits: 0
  sitefarm_article: 0
  sitefarm_auth: 0
  sitefarm_basic_block: 0
  sitefarm_core: 0
  sitefarm_custom_actions: 0
  sitefarm_custom_social_links: 0
  sitefarm_event: 0
  sitefarm_focal_link: 0
  sitefarm_focus_box: 0
  sitefarm_hero_banner: 0
  sitefarm_image_styles: 0
  sitefarm_marketing_highlight: 0
  sitefarm_page: 0
  sitefarm_person: 0
  sitefarm_photo_gallery: 0
  sitefarm_simple_configuration: 0
  sitefarm_summary: 0
  sitefarm_wysiwyg: 0
  sitemap: 0
  smtp: 0
  social_media_links: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  trumba: 0
  uc_credits: 0
  uccsc_event: 0
  uccsc_sponsors: 0
  uccsc_user: 0
  url_embed: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  sitefarm: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  sitefarm_one: 0
  uccsc2018: 0
profile: sitefarm
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
