unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: true
  user_pass: true
  contact_message_feedback_form: true
  contact_message_personal_form: true
  node_event_form: true
  node_session_form: true
  node_sf_article_form: false
  node_sf_event_form: false
  node_sf_page_form: false
  node_sf_person_form: false
  node_sf_photo_gallery_form: false
  node_uccsc_sponsor_form: false
  node_venue_form: false
_core:
  default_config_hash: HM89l2a_SP7lC9C_a_THjoKamMbJ1Ne7yTPQpPBQ6bI
