name: sf_gallery_thumbnail
label: 'Gallery Thumbnail'
langcode: en
status: true
dependencies: {  }
effects:
  sf_gallery_thumbnail_focal_point_scale_and_crop:
    uuid: sf_gallery_thumbnail_focal_point_scale_and_crop
    id: focal_point_scale_and_crop
    weight: 1
    data:
      width: 352
      height: 198
