links:
  -
    path: /
    priority: '1.0'
  -
    path: /blog
    priority: '0.9'
  -
    path: /news
    priority: '0.9'
  -
    path: /events
    priority: '0.9'
  -
    path: /people
    priority: '0.7'
  -
    path: /photo-galleries
    priority: '0.7'
_core:
  default_config_hash: ug-g5MWHXjFPdr9nUmur2bdo_yBdwoURwCGvjs-uuN8
